# Generated by Django 5.0.6 on 2024-06-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letting',
            old_name='address',
            new_name='addresses',
        ),
    ]
