name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   run: flake8  // check pep8 et pytest si non exit => pas build image

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/p13:latest -f Dockerfile . 

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/p13:latest

      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            docker stop p13 || true
            docker rm p13 || true
            docker rmi ${{ secrets.DOCKER_USERNAME }}/p13 || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/p13:latest
            docker run -d --name p13 -v /home/ubuntu/db/oc-lettings-site.sqlite3:/app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/p13
          EOF
